name: node pipeline test

on: push

env: 
  ARTIFACT_NAME: hello_test

jobs:
  build:
    name: pre Build and test
    runs-on: ubuntu-latest
    steps: 

    - name: check out code
      uses: actions/checkout@v2
    
    - name: update apt
      run: sudo apt update

    - name: install npm
      run: sudo apt install npm -y

    - name: run hello.js
      run: node hello.js

  upload:
    name: upload artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
    
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.ARTIFACT_NAME}}
        path: .

  test:
    name: test
    runs-on: ubuntu-latest
    needs: upload
    steps: 

#     - name: check out code
#       uses: actions/checkout@v2

    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: hello_test
    
    - run: pwd
    - run: ls -al
    
    - name: update apt
      run: sudo apt update

    - name: install npm
      run: sudo apt install npm -y

    - name: run hello.js
      run: node hello.js

